version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: aswinhariram/ocrgenie-frontend:latest
    
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: aswinhariram/ocrgenie-backend:latest
